name: Deploy to GitHub Pages

on:  
  workflow_dispatch
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install dependencies
      run: npm ci

    - name: Build and deploy
      run: |
        npm run build
        npm exec gh-pages -d dist -b gh-pages -u "github-actions-bot <support+actions@github.com>"
        # npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
