name: Deploy to GitHub Pages

on:  
  workflow_dispatch
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install dependencies
      run: npm ci

    - name: Build and deploy
      run: |
        npm run build
        npm run deploy
      env:
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
